### ISSUE TITLE
I run mcserver_installer.sh, but it starts writing some text really fast, and stops working without opening any dialogs(Servers folder still get created)

### ISSUE THREAD

**Issue by alwayshyper** [officialrealTM/mcserver_installer#4]
Please fix it it worked previously, but when i erased the vm it stoped

**Comment by alwayshyper** [comment]
the issue is that script requires package "dialog"

**Comment by officialrealTM** [comment]
@alwayshyper I've tested the Script yesterday and it worked fine!
The "dialog"-package is **required** to run this script - It has been the foundation of it since day one, so it can't be an issue with this package.

Please give me more details about your error, e.g.:
- On what operating system are you using the script
- Which Version of Minecraft do you want to install (Vanilla, Forge, Spigot or Paper)
- Which Minecraft version are you trying to install (e.g. 1.8.9, 1.20.1...)

You are also welcome to join my Discord server and create a Support-Ticket over there, so I can help you.
Join [here](https://realtm.link/discord).

Please respond to this message, otherwise the Issue will be closed!

Regards

realTM
